spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/p3java-airecommendation-db
      database: p3java-airecommendation-db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083